### PR TITLE
Bugfix/optimize explorer page scrolling

### LINKED ISSUE #134: Optimize Explorer Result Page to Use Lazy Loading for Improved Performance
**Problem:**
The current implementation of the ExplorerResultPage utilizes a SingleChildScrollView with a Column, where all transaction items are loaded and built at once. This leads to performance issues, including noticeable lag and jank during scrolling, particularly when handling a large number of transactions.

**Steps to Reproduce:**
1- Navigate to the Explorer section from the BottomNavigationBar.
2- Tap on the search icon
3- Paste a public ID that has many transactions (e.g., EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVWRF).
4- Click view details
5- Scroll through the page and observe the performance—notice the significant lag during scrolling.

### PR DESCRIPTION
**Pull request by ahmed-tarek-salem**
**Changes**
- Replaced SingleChildScrollView and Column with SliverList.builder, which builds items lazily on demand as they are scrolled into view in ExplorerResultPageQubicId and ExplorerResultPageTick.
- Optimized rendering by only building the visible transaction items, reducing the load on the UI and improving performance.

Fixes #134

### CODE REVIEW

File: lib/components/explorer_result_page_tick/explorer_result_page_tick.dart [hunk 1]
```diff
@@ -88,28 +86,39 @@ class ExplorerResultPageTick extends StatelessWidget {
...
+          padding: EdgeInsets.only(
+              left: ThemeEdgeInsets.pageInsets.left,
+              right: ThemeEdgeInsets.pageInsets.right),
+          sliver: SliverToBoxAdapter(
+            child: getTransactionsHeader(context),
+          ),
+        ),
+        if (tickInfo.transactions != null && tickInfo.transactions!.isNotEmpty)
+          listTransactions(),
+        // Padding(
```
Comment (sallymoc) [inline lib/components/explorer_result_page_tick/explorer_result_page_tick.dart:111]: if we won't use the commented code, please remove

Comment (ahmed-tarek-salem) [reply lib/components/explorer_result_page_tick/explorer_result_page_tick.dart]: Done
